[tool.black]
line-length = 100

[tool.poetry]
name = "cv"
version = "2.0.1"
description = "Programatically create CVs"
authors = ["Alex Thola <alexthola@gmail.com>"]
maintainers = ["Alex Thola <alexthola@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/athola/cv"

[tool.poetry.dependencies]
python = "^3.8.0"
flask = "^2.2.3"
markdown = "^3.4.1"
oyaml = "^1.0"
httpx = "^0.24.1"
weasyprint = "^59.0"

[tool.poetry.group.utils.dependencies]
pillow = "^9.4.0"
pydantic = "^1.10.6"
tqdm = "^4.65.0"
vpalette = "^3.0.0"
pylint = "^2.17.4"

[tool.poetry.scripts]
generate_pdf = "cv:generate_pdf"
run_app = "cv:run_app"

[tool.pylint.master]
recursive = true
ignore = [
    "static",
    "templates"
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
